### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by intesticle** [gogo9211/Roblox-Woof#2]
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\andre\AppData\Local\Roblox\Versions\version-bcf2153e4dc94025\XInput1_4.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at _268_kick_fixer.Program.Main(String[] args)

**Comment by iisigma** [comment]
yeah you are def autistic
